name: Build and Deploy Android App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Set up Gradle
      run: chmod +x gradlew
    - name: Build and Increment Version
      run: |
        ./gradlew app:incrementVersion
        ./gradlew assembleRelease
      env:
        RELEASE_KEY: ${{ secrets.RELEASE_KEY }}

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: app-release
        path: app/build/outputs/apk/release/app-release.apk